### ISSUE TITLE
is the project being maintained?

### ISSUE THREAD

**Issue by rickmed** [hainproject/hain#177]

**Comment by blainesch** [comment]
There was a commit a day ago by the creator on a feature branch.

https://github.com/appetizermonster/hain/branches

**Comment by rickmed** [comment]
I see a _bit_ of activity on that branch but not much more anywhere else (from months). Not trying to be obnoxious just asking

**Comment by appetizermonster** [comment]
Hi, to be honest, it's not actively maintained. but i'm very struggle to commit something which makes `hain` better.
For now, Complex architecture of hain makes me hard to add some features. so I'm trying to refactor this first.

**Comment by rickmed** [comment]
@appetizermonster I love this project (been wanting to build one myself for a few weeks until I found this) so thank you for the response! Not sure if/how can immediately contribute but would love to in the coming weeks.

**Comment by appetizermonster** [comment]
Thanks!

**Comment by rickmed** [comment]
@appetizermonster Should we wait until the refactor is finished? I may want to slowly start involving myself with things like simple plugins.

**Comment by appetizermonster** [comment]
you can start making plugins immediately. there will be no changes for plugin interface.
but there will be only internal structure changes. so if you want to submit new feature PR, it may not be merged immediately.

**Comment by rickmed** [comment]
so you'll accept it after the refactor is complete?

**Comment by appetizermonster** [comment]
@rickmed Yes i will

**Comment by TheElf** [comment]
I found this linked off of the electron homepage while I was working on a simple plugin system (think like this with no features and niceties, just the plugin context object)

I would be highly interested in working on this with you guys, let me know what kinds of work you would like done.

I'm:
 - mostly competent with 
  - node
  - electron
  - powershell
 - highly competent with
  - .net/windows programming (recently acquired/used through work)
  - html/css
  - graphic design
  - typescript (if you guys want a rewrite lol)
  - client javascript (webpack/react/bower[although i just use npm now])

**Comment by cpriest** [comment]
Im highly interested in contributing as well, fluent in JS and some electron.  What can we help with?

Is the refactoring complete?

Ive written my own plugin or hain already but dislike the preference UI thats available, not sure if there are any plans to change/improve that or not.

**Comment by staff0rd** [comment]
It seems there's a fair amount of people keen to contribute but the owner's lack of time available to commit is holding the project back.  I wonder if he'd be interested in allowing the community to drive it forward, maybe by endorsing a project manager who could facilitate the creation of a roadmap and/or design goals for the project, and to clean up the open issues and PRs.

**Comment by appetizermonster** [comment]
Sorry for the late.
@cpriest Yes! the refactoring has completed after v0.5.0
@staff0rd 
As you said, Currently I'm super busy. so i couldn't handle this project at the right time.
and Yes, I'd like to make this project open for the community :-) 
however I have no idea how to make it open.
I'm very beginner for the open source project culture. 
I would appreciate it if anyone could tell me any idea for the change.

**Comment by toXel** [comment]
@appetizermonster Maybe it would be a first step to create a GitHub organization and move to repo(s) to it. Then it's very easy to choose some project maintainers who can also merge PRs or make decisions.

A project where this model works very good is [The Lounge](https://github.com/thelounge/lounge). There all PRs have to be reviewed by 2 maintainers and then can be merged.

GitHub organizations are free for open source projects.

**Comment by appetizermonster** [comment]
@toXel Thanks for letting me know a nice project model. I need to take a look at "The Lounge" project and Github Organization :smiley:

**Comment by cpriest** [comment]
FTR, I'm working on the project as a contributor.  Most anyone (at the moment) can fork the project, build something and submit a pull request.  I'm looking through the pull requests and working on some of the tickets as well.

**Comment by cpriest** [comment]
Some great news in this regard, @appetizermonster has made hain into an organization and it's being actively developed.  I'm working on a few tickets here and there and actively looking for additional help.  Going to keep this ticket open, if anyone wants to get involved or keep updated we now have a mailing list you can join to ask questions of those involved.

You can join by sending an email with subscribe in the subject line to hain-request@freelists.org.

**Comment by dannya** [comment]
@cpriest I'd like to suggest closing this issue
