### ISSUE TITLE
chocolately version is 0.3

### ISSUE THREAD

**Issue by hans-d** [hainproject/hain#205]
please upgrade the package

**Comment by appetizermonster** [comment]
Sorry for the late update, because I'm not familiar with Chocolatey environment.
I'll try.

**Comment by ferventcoder** [comment]
Would you like some assistance? We have some folks who could help. I have a request for maintainers (RFM) for this in the community package repository.

**Comment by cpriest** [comment]
That would be great, anyone willing to contribute would be a big help.

**Comment by ferventcoder** [comment]
I will ask them to reach out directly.

**Comment by TakataSanshiro** [comment]
Hi, I'm Sanshiro, the new maintainer of hain chocolatey package.
I've submitted the latest hain package, and I continue to updated one.
https://chocolatey.org/packages/Hain/0.6.4

**Comment by appetizermonster** [comment]
@TakataSanshiro Thanks for your contribution!!

**Comment by vertigo220** [comment]
I see Chocolatey support was removed in a recent update. Why was that done?
