### ISSUE TITLE
런칭 이후 다시 하인으로 앱을 부를 때 새로운 인스턴스를 띄우는 문제

### ISSUE THREAD

**Issue by soomtong** [hainproject/hain#210]
건의 드릴게 있어요.

하인으로 앱을 런칭 한 후 (예를 들면, 크롬 브라우저) 다시 하인으로 그 앱(크롬)을 부르면 그 앱(크롬)의 새로운 창이 뜹니다. 혹시 새로운 창이 아니라 기존에 있는 앱을 포그라운드로 불러오는 것이 가능할까요?

많은 앱들이 새로운 인스턴스를 띄우는데 살짝 불편한 부분이라 생각합니다.

좋은 앱 감사합니다!

**Comment by appetizermonster** [comment]
늦게 답변 드려서 죄송합니다.
기존에 있는 앱을 포그라운드로 불러오는 건 지금은 어떻게 구현해야 할지 모르겠네요.
일반적으론 그건 Chrome에서 처리해야하지 않을까 싶어요.
아니면 https://github.com/freakzero/hain-plugin-cmdow 같은 플러그인을 이용하거나
비슷한 플러그인을 만들어야 가능할 것 같네요.
감사합니다.

**Comment by cpriest** [comment]
no idea what this is about, @appetizermonster  can this be closed?

**Comment by appetizermonster** [comment]
@cpriest it's okay to close the issue. i'm closing it
