### ISSUE TITLE
Input bar design

### ISSUE THREAD

**Issue by vladamx** [hainproject/hain#216]
Hello,

First, let me thank you for this beautiful piece of software. It's really great.

However, I would like to discuss "too much in the face" color of the input bar.
I would like it slightly less opinionated and easier for the eye with slightly more padding. 

Thanks.

**Comment by appetizermonster** [comment]
If you have any better design, you can make pull request or upload your ui design image in this issue.
I thought Hain should be redesigned. I have no idea though.

**Comment by dannya** [comment]
My changes for extensive theme support are now in develop, so I consider this implemented.
