### ISSUE TITLE
Attempting to close an open window with hotkey refreshes it instead

### ISSUE THREAD

**Issue by aouerfelli** [hainproject/hain#224]
Hain version: 0.6.1
OS: Windows 10 (x64)

Issue: When the Hain window is open and you attempt to close the window via the global accelerator (alt+space in my case), the window is refreshed instead of closed.

**Comment by cpriest** [comment]
The global accelerator shows the window, you can close it with Esc.

**Comment by cpriest** [comment]
Although I do have to say this is a change in behavior from a recent commit of mine, which was related to pressing a global shortcut (with an input) while the window was open, would cause it to close.  The same would have been true of Alt+Space which is why it no longer closes it.

**Comment by aouerfelli** [comment]
I see where you're coming from, but from a convenience standpoint, I still believe that having the window state toggle is more convenient (which is what the program is essentially about). I guess adding an option to preferences (as suggested in #220) is the best course of action.

**Comment by cpriest** [comment]
@appetizermonster
We'll add a preference option to use toggle vs show, per #220.

On the other hand, it could function better simply by using .show() when there is a query present (from a global shortcut -> query mapping) or .toggle() if no query is present (from Alt+Space).

Thoughts?

**Comment by appetizermonster** [comment]
@cpriest Sorry for the late, that option seems not bad.
