### ISSUE TITLE
hain-plugin-math: Rounding issue

### ISSUE THREAD

**Issue by ChristopherHaws** [hainproject/hain#228]
Hello,

There seems to be a rounding issue with the built in calculator.

**Steps to reproduce**
1. Open Hain
2. Type `=0.1+0.2` into the search bar

**Expected behavior**
I would expect for the result to be `0.3`

**Actual behavior**
The result is showing up as `0.30000000000000004`

![image](https://cloud.githubusercontent.com/assets/5934505/24315328/a5fcd36a-10a3-11e7-943f-88bea8090586.png)

Thanks!

**Comment by cpriest** [comment]
Welcome to the strange world of floating point arithmetic on computers...

Not that we won't look into it though, that is an odd one.

**Comment by ChristopherHaws** [comment]
Looks like the "fix" is to use `toFixed`. I'm not sure the best way for you to determine how many decimal places to show however.

http://stackoverflow.com/questions/10473994/javascript-adding-decimal-numbers-issue

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed
