### ISSUE TITLE
Error: Plugins gone after reload

### ISSUE THREAD

**Issue by stefanpawlik** [hainproject/hain#238]
Hi,

I hope I'm not doing anything wrong. 
After I install any plugin, they initially appear in the /hpm list, but are not usable, which is normal. Once I do the requested plugin-reload, they are not accessible anymore. They also do not appear in the /hpm list, only the standard plugins are available. A restart of Hain does not fix this issue for me.
However, the folders are present on my harddrive. 

Tested on 2 Win10 machines. Hain version 0.6.3

Cheers,
Stefan

**Comment by appetizermonster** [comment]
Thanks for the issue, I'll look at it

**Comment by Joni4Games** [comment]
Same problem here.

Win 8.1 x64-Bit, Hain v 0.6.3

**Comment by appetizermonster** [comment]
`hain-package-manager` uses the `tarball-extract` module to extract downloaded archive files.
but the module is broken with its dependency for now.
so i fixed it temporarily by the commit 9ae862f8ae4569bb4b0aba0ca612ef1f5df3313e

https://github.com/joshuah/tarball-extract/issues/8

**Comment by appetizermonster** [comment]
this issue has resolved with the v0.6.4
