### ISSUE TITLE
draggable?

### ISSUE THREAD

**Issue by iulo** [hainproject/hain#241]
platform: win10

**Comment by lawgsy** [comment]
This is currently not possible.

If this is going to be added in the future, here's a quick round-up for the one who wishes to implement this:
- The main body should have as CSS: `-webkit-app-region: drag`
- The window should record the position upon closing and restoring to last known location upon opening
- All clickable non-input elements (possibly others) must have `-webkit-app-region: no-drag;` as css (I applied it to all span elements and it seemed to work just fine on the UI itself)

You would then be able to drag the window while holding down ctrl (I have only tested the above on Windows 10 through the developer window and was able to drag just fine).

See [Electron API (Frameless Window)](https://github.com/electron/electron/blob/master/docs/api/frameless-window.md)

**Comment by dannya** [comment]
Merged into develop.
