### ISSUE TITLE
Custom plugin doesn't show up

### ISSUE THREAD

**Issue by SirWindfield** [hainproject/hain#242]
I created a custom plugin for hain but it doesn't seem to get listed within the application. It is [this](https://www.npmjs.com/package/hain-plugin-jisho-org) one here. 
Does it take some time until npm or hain reindex the repo?

I saw that there is already one for jisho, but I was planing to add more stuff. Just wanted to test the api first.

**Comment by cpriest** [comment]
Just looking over another plugin, looks like you're missing the URL from your package.json file...

https://github.com/kenji-getpowered/hain-plugin-google-map/blob/master/package.json

**Comment by SirWindfield** [comment]
@cpriest I updated my package.json file and pushed again to npm but it still doesn't show up D:
Sorry if I am annoying but I just can't get it to work.

**Comment by cpriest** [comment]
I'm not sure offhand, I'm not too familar with that code just yet.  You might look at some other packages that are working with /hpm and see what their package.json file looks like.  To my knowledge the only requirements are what is listed on the documentation pages.

**Comment by SirWindfield** [comment]
Found the error I think. Looks like hain's latest API version is just `0.5.0` and not `0.6.0` as mentioned in the docs. [Here](https://github.com/hainproject/hain/blob/73ebd0b7993f20433fc33169837c16b90550d563/app/package.json#L7) is the relevant json file if I am not mistaken.

**Comment by cpriest** [comment]
Hmm that would be strange, perhaps a bug.  Assuming you're running the latest release.
null

**Comment by SirWindfield** [comment]
Running Hain v0.6.4, changed the plugin keyword to `hain0` but it still doesn't show up D:

**Comment by appetizermonster** [comment]
I could find your plugin (`hain-plugin-jisho-org v0.0.5`) on my Hain v0.6.4 on macOS.
maybe it took time to index npmjs registry by npmsearch.com which is used by Hain for searching plugins if you don't touched your plugin.
