### ISSUE TITLE
File Search won't show results.

### ISSUE THREAD

**Issue by drnhzn** [hainproject/hain#245]
Can't seem to make File search plugin to work. It doesn't show anything. Tried to restart my Computer and still nothing. Thanks!

**Comment by sethxd** [comment]
What are your preferences set to? Mine, for example, looks like this:

![image](https://user-images.githubusercontent.com/3084071/29383394-3ebc90c4-829e-11e7-8816-09d93b02ea3f.png)

**Comment by dannya** [comment]
@drnhzn did the steps above resolve your issue? Do you have more information on this? Thanks.

**Comment by dannya** [comment]
Closing as no response.
