### ISSUE TITLE
Suggestion: Calculator - decimal point preferences

### ISSUE THREAD

**Issue by stefanpawlik** [hainproject/hain#246]
Hello everyone,

being from Europe means I use a comma as decimal point instead of the [American/Asian dot](http://www.statisticalconsultants.co.nz/blog/how-the-world-separates-its-decimals.html).

A cool feature would be to allow the user to choose their prefered decimal point in the preferences or even allow for both directly during input.

Cheers,
Stefan

**Comment by dannya** [comment]
@stefanpawlik implemented in https://github.com/hainproject/hain/pull/268 , currently pending code review for inclusion in the next release

**Comment by dannya** [comment]
Now in develop,
