### ISSUE TITLE
Adding another drive?

### ISSUE THREAD

**Issue by akhilkathi97** [hainproject/hain#249]
How to add another drive to HAIN to look up for search i.e. Folders to search recursively?

**Comment by AndisGrossteins** [comment]
1. Launch Hain
2. type `/hain` and click on Open Preferences
3. On the left side, you'll see a list of plugins
4. Click on `hain-plugin-filesearch` and click the <kbd>+</kbd> button to add a new entry
5. Just type whatever path you want Hain file search to index and you're done

**Comment by dannya** [comment]
@akhilkathi97 did the steps above resolve your issue? Thanks.

**Comment by dannya** [comment]
Closing as no response.

**Comment by welch08** [comment]
I've some problem like this

I'm added drive in preferences but nothing changed
http://prntscr.com/n98n9f
