### ISSUE TITLE
Abandoned or long Hiatus?

### ISSUE THREAD

**Issue by braydenhouston** [hainproject/hain#252]
I have been looking to develop a few plugins for Hain. I noticed it has been pretty quiet around the repo and previously reported issue threads.

Just was curious if this project is on a hiatus or if it has been abandoned. I really like the appeal of developing node.js based launcher.

I tried testing the waters on Hain's activity by submitting #251. However, there doesn't seem to be any maintenance being done let alone new changes.

My main issue is that any recently developed plugins don't seem to have a way to be distributed because 'hpm' is leveraging http://npmsearch.com which also seems to be a possibly abandoned project. This means if I was to make any plugins I would be a little difficult to pass any around with any great success.

Are there any plans for development to resume on Hain?

**Comment by appetizermonster** [comment]
First of all, Thank you for trying to contribute this project. 
To be honest, You can say this project is abandoned. I'm quite busy these days and the project is quite complex to handle properly for myself.
I love this hain project and launcher program bulit with JavaScript.
And I learned many lessons from this prouect. So I have a plan for writing new launcher with TypeScript. But it may takes long time to start the work and it will be a different project.
Thank you again.

**Comment by braydenhouston** [comment]
Good to know. I'll have to start looking for a new launcher again.

I hope to see your new Typescript project one day.

**Comment by notatestuser** [comment]
Seems like it might be trivial to make hain use another npm search provider. Have you considered handing this project to a more active maintainer @appetizermonster?

**Comment by appetizermonster** [comment]
@notatestuser Yes, I'm open to hand over this project to another maintainer. Do you have a mind?

**Comment by braydenhouston** [comment]
I am interested in helping to contribute and keep Hain going. Perhaps not being the owner but I am definitely interested in joining development effort if other are looking in to join too.

**Comment by cpriest** [comment]
@appetizermonster Perhaps we can work on the new launcher together?  I have not 'abandoned' this project per say, but have been on a long hiatus.  (I can't remember ever having been so busy as the last 5 months).

I too think starting over with a new launcher makes sense, this was a great first effort but the current code complexity warrants a new strategy.

**Comment by appetizermonster** [comment]
@cpriest 
I agree that this project is too complex to add new features easily. and I just want to say I really thanks for your contributions!

I just have a plan for writing a new launcher in TypeScript, but it's not easy to be having time to make it as I have to spend most of my time to my real job.
but someday (maybe later in this year), I will do it.

Or you just can start your own project, and then I think I can contribute to it.

**Comment by cpriest** [comment]
It'd be nice to get a few people in addition to you and I on board with 
a rewrite. Anyone else interested or know of anyone who'd be interested?

**Comment by braydenhouston** [comment]
@cpriest 

I would be interested in contributing!

**Comment by cpriest** [comment]
Alright, when I get some time I'll get a community project page put 
together and we can decide on some plans/goals, etc.  I'll post about it 
here.

**Comment by cpriest** [comment]
Hey @appetizermonster and @braydenhouston I created an organization (MotleyCoders) and project (design) with a few basic wiki pages we can use to get started.  You should both have received an invitation.

The idea of starting anew kept me up a bit last night so I thought I'd get the ball rolling sooner than later.  https://github.com/MotleyCoders/design/wiki

**Comment by cpriest** [comment]
Thank You @notatestuser.  I'll link to this in the project wiki as well.

**Comment by appetizermonster** [comment]
I've joined the organization, Good work! @cpriest

**Comment by cpriest** [comment]
If anyone would like to join the discussions so far or the project in general, even for ideas or for testing.

https://github.com/orgs/MotleyCoders/teams/design

If you can't post there, msg me or post on this thread.
