### ISSUE TITLE
[v0.6.5] No icon in the search results

### ISSUE THREAD

**Issue by yusiwen** [hainproject/hain#262]
I've updated hain to the latest release(0.6.5) and found there are no icons in the search results list, like the screenshot below:

![image](https://user-images.githubusercontent.com/3704932/39977917-a7f5f2c8-576f-11e8-8589-477b03d2a008.png)

**Comment by appetizermonster** [comment]
Thank you for the reporting, I think i've missed rebuilding native module for Windows (because I'm using macOS only for now)
I'll try to fix it soon
