### ISSUE TITLE
Is there anyway to get rid of the button control icons on the search bar?

### ISSUE THREAD

**Issue by thedonquixotic** [hainproject/hain#274]
Themes seem to primarily address color scheme so I wasn't sure if that could be used.  Also Is it not possible to theme things further with stuff like rounding corners adjusting padding etc?

**Comment by dannya** [comment]
I plan to make this a config option in the future.

For further theming, we are limited by 2 things:
* What Electon and the Material Design UI widgets allow us to theme
* Remaining compatible with the Alfred theme format

**Comment by thedonquixotic** [comment]
👍

**Comment by thedonquixotic** [comment]
Loving it so far! Keep up the good work! I'll be sure to include this on a new work pipeline post for devs that I'm writing up.

**Comment by thedonquixotic** [comment]
Hey @dannya btw, wanted to let you know that I linked Hain on slant.co https://www.slant.co/topics/3945/viewpoints/25/~linux-app-launchers~hain

I use slant for most of my software recommendations and I was surprised that Hain wasn't already up there. Thank you for the work you're doing on Hain! It's a really well done project and I hope to see use and support for it grow and spread :)
