### ISSUE TITLE
New plugin not appears in hpm

### ISSUE THREAD

**Issue by popstas** [hainproject/hain#278]
Hello, I published plugin 2 months ago - https://www.npmjs.com/package/hain-plugin-puttytray, but it not available with `/hpm install`.
Here is the [package.json](https://github.com/popstas/hain-plugin-puttytray/blob/master/package.json), what did I do wrong?

**Comment by appetizermonster** [comment]
Oh Sorry, your `package.json` contains a keyword `hain-0.6.0`. but it looks like that isn't supported now. please add keyword `hain-0.5.0` :)

**Comment by popstas** [comment]
Thank you!
