### ISSUE TITLE
How to actually use themes?

### ISSUE THREAD

**Issue by chriscubellis** [hainproject/hain#279]
Hi - this might be more of a general confusion than an issue, but how do  I actually use themes? I was reading docs/themes.md & saw that its supposed to come preinstalled with dark & light, but I don't see anywhere within Hain to change the theme to the dark one? Is this supposed to be in the settings?

I also saw in that same doc that there's supposed to be a /themes folder in 
"C:\Users\danny\AppData\Local\hain-user\themes", but it's not there for me...

**Comment by thedonquixotic** [comment]
@chriscubellis Just create the folder if it's not already there for you.

**Comment by chriscubellis** [comment]
@thedonquixotic i had, but...what am i supposed to be putting into it? and where am i supposed to be changing what theme is active? All I really want to do is use the dark theme that's supposed to be bundled with this...

**Comment by thedonquixotic** [comment]
Unfortunately I can't help you there. After having trouble getting Hain to work on my linux machine and then finding some of the plugins that I used broke I've sinced moved to Listary. It's closed source which is a bummer but it's also BY FAR the most powerful app launcher I've found. It's really fucking dope. https://www.listary.com/pro

**Comment by dannya** [comment]
@chriscubellis I replied by email to the GitHub notification, but it hasn't appeared here!

If you're using a version of Hain that supports themes, there are options in the settings UI for it. If there are no UI options for theming, you will need to upgrade to the latest version.

**Comment by chriscubellis** [comment]
No worries! Is 0.6.6 not a version with themes? It's the latest on the releases page and I'm not seeing any theme options in the preferences...

**Comment by appetizermonster** [comment]
@dannya Yep, I'll release a new release asap

**Comment by dannya** [comment]
@appetizermonster are you able to do the release soon?

**Comment by appetizermonster** [comment]
Sorry for the late 😢I couldn't invest much time in this project, I'll try to release a new version in a week.

**Comment by appetizermonster** [comment]
@dannya I made the release for new version `v0.7.0-beta.1`, but I don't have a Windows PC for now 😢 
Could you test the new build before the public release :)

**Comment by Phibonacci** [comment]
I have spent 20 minutes looking for a way to select the default black theme. You should add a note [to the wiki](https://github.com/hainproject/hain/blob/develop/THEMES.md) about the last release not having theme support.

**Comment by TheethumNandrum** [comment]
+1 on documenting this in the Wiki. I spent hours trying to get this work.  Tried workaround @wjvander mentioned and it no longer works. The project doesn't build on Windows (seperate issue, don't want to hijack this thread).

**Comment by fc757** [comment]
I just compiled the v0.7.0-beta.1 version. I put it up on my website if anybody would like to use it to check out the themes and whatever else is new. Have at it:

https://cetialphafive.com/~fc/hain/

Obligatory Khaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaan!!!!!

**Comment by TheethumNandrum** [comment]
Thanks, that works!!

**Comment by fc757** [comment]
> Thanks, that works!!

For one, shimmering moment, I had purpose! Glad it worked for you. +10 to your micro.

**Comment by dannya** [comment]
@fc757 @TheethumNandrum the issue that was holding us back from officially releasing this was: https://github.com/hainproject/hain/issues/279#issuecomment-439705322

Can you please test if you can reproduce this on this new Windows build package that you've created, and report back your findings? Thanks.

**Comment by fc757** [comment]
No unhandled errors for me when I enabled transparency or when I close it/open it after enabling with the 0.7.0-beta.1 build I made. But I did try to use Hain instinctively to open it back up after I closed it for the test :)

I'm running Win10 Edu 1803 build 17763.316 and GTX 1060 with driver 418.91.

https://cetialphafive.com/~fc/hain_transparency.png

**Comment by alanaasmaa** [comment]
I downloaded the latest version also. But i can't get the team to work.

I stored this file into themes folder and restarted but it does not seem to detect it.
https://github.com/dracula/alfred/blob/master/Dracula.alfredappearance

**Comment by TheethumNandrum** [comment]
@dannya tested with transparency. No unhandled exceptions / crash for me either. I'm on Win10 Build 17134.590 with Intel HD Graphics.

**Comment by dannya** [comment]
@alanaasmaa unfortunately any themes containing serialized NSColor objects that are not parsable, so if this is detected the file is not loaded (if you know of a way to decode these in JavaScript, please let me know!).

Example:

```
<data>
	BAtzdHJlYW10eXBlZIHoA4QBQISEhAdOU0NvbG9yAISECE5TT2JqZWN0AIWEAWMBhARm
	ZmZmg85vDT+DEE1PP4O/JKA+AYY=
</data>
```

**Comment by dannya** [comment]
@appetizermonster two people above have reported no issues with the test build containing theming on Windows, so maybe it can be officially released now?

**Comment by appetizermonster** [comment]
@dannya Thanks! I'll build and release it very soon (maybe today or tomorrow?)

**Comment by anandcu3** [comment]
@appetizermonster Will you be releasing a new version soon?
