### ISSUE TITLE
/hpm install: Error occured

### ISSUE THREAD

**Issue by popstas** [hainproject/hain#282]
![image](https://user-images.githubusercontent.com/3027126/49941898-9dabc700-ff05-11e8-8cde-5a578c2aef84.png)

Hain 0.6.6
Trying to /hpm update and /hain restart

**Comment by popstas** [comment]
I published plugin [hain-plugin-ansible-server-site](https://www.npmjs.com/package/hain-plugin-ansible-server-site) several hours before, possible it can break hpm install

**Comment by Eeems** [comment]
@popstas It's possible that hain is falling over trying to handle the character set you are using in the readme.
@appetizermonster Any chance you can take a look soon and push out a fix for 0.6.6?

**Comment by popstas** [comment]
@Eeems, agreed, trying to remove non-english chars from readme.

**Comment by popstas** [comment]
It solved problem!

**Comment by Eeems** [comment]
Confirmed! Thanks!
