### ISSUE TITLE
Supporting Themes from .tmTheme files

### ISSUE THREAD

**Issue by jieverson** [hainproject/hain#82]
Lots of stuff developed with electron support themes (_Atom_, _Slack_, _VSCode_).
I'm talking about colors, foregrounds, fonts, etc... just things that don't make it heavy.
Themes could be loaded from a simple _.tmTheme_ file. Examples can be found here: http://colorsublime.com/

If I have some free time next week I will take a look at the code, maybe I can give a little help.
![asdasd](https://cloud.githubusercontent.com/assets/1031323/14215330/ad4984e6-f818-11e5-8455-9e341341e004.png)

**Comment by ewnd9** [comment]
@jieverson Do you have any references to an implementation for electron apps?

---

Btw this is how dark theme may look like (I've manually overridden css in my local fork) 

![Demonstration](http://i.imgur.com/f0MuCJY.png)

```diff
---
 app/dist/index.html | 6 +++++-
 1 file changed, 5 insertions(+), 1 deletion(-)

diff --git a/app/dist/index.html b/app/dist/index.html
index 5851cf7..3c64bc9 100644
--- a/app/dist/index.html
+++ b/app/dist/index.html
@@ -23,6 +23,10 @@
       overflow: hidden;
       font-family: 'Roboto', sans-serif;
       font-weight: 400;
+      background: #424242;
+    }
+    body * {
+      color: #FAFAFA !important;
     }
   </style>
 </head>
@@ -32,4 +36,4 @@
     require('../renderer/app.js');
   </script>
 </body>
-</html>
\ No newline at end of file
+</html>
-- 
1.9.1
```

**Comment by ishu3101** [comment]
What about supporting themes from Alfred or Wox?

**Comment by Metrakit** [comment]
Look nice @ewnd9

**Comment by jieverson** [comment]
Great job @ewnd9 
Loved it :)

**Comment by ewnd9** [comment]
@ishu3101 supporting themes from other launchers is a great idea since you could see how it looks before downloading and installing, I think it should be implemented first.

As for realisation details, `tmTheme` seems a little redundant, it would be easier to allow to just add a CSS file with style overloading in settings.

**Comment by raisedadead** [comment]
Yup, I would love to see if we can simply support Alfred themes. They are simple JSON formats. For instance:

https://github.com/dracula/alfred/blob/master/Dracula.alfredappearance

Parsing in that and storing it whatever architecture hain has would be a smart idea, considering Alfred has hundreds of themes already and they have a standard format for most.

**Comment by rahulpsd18** [comment]
Any updates on this? Thankyou for your awesome work.

**Comment by dannya** [comment]
@rahulpsd18 I just need to refactor my pull request a little to better support transparency on Mac OS, hoping to have this done by the end of this week.

**Comment by dannya** [comment]
This has now been merged into develop, including support for blurred window backgrounds on MacOS.

![hain_light_mac](https://user-images.githubusercontent.com/394687/40999442-cc98c8d6-6902-11e8-8005-86f2a894927f.png)
![hain_dark_mac](https://user-images.githubusercontent.com/394687/40999445-ce4d3afe-6902-11e8-8462-b18e264649c5.png)
