### ISSUE TITLE
Loading "Preferences" window

### ISSUE THREAD

**Issue by Semigradsky** [hainproject/hain#89]
Maybe add some spinner? On my notebook I see a white screen for 6-7 seconds.

**Comment by appetizermonster** [comment]
@Semigradsky It is needed if time is taken to load preferences window, I will be working on it

**Comment by appetizermonster** [comment]
It is implemented with [v0.2.0](https://github.com/appetizermonster/hain/releases/tag/v0.2.0), but there is room for improvements yet.

**Comment by dannya** [comment]
My changes to this are now merge into develop so I consider this issue resolved - please check out develop or see the changes in the version after v0.6.6 (beta) is released.
